name: Do a Duolingo lesson

on:
  workflow_dispatch:
    inputs:
      lessons:
        default: 1
        description: 'Number of lessons to be done'
        required: false
        type: number
      secondary_lessons:
        default: 1
        description: 'Number of lessons to be done on secondary account'
        required: false
        type: number

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: ${{ inputs.lessons }}
  secondary_study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_SECONDARY_JWT }}
          LESSONS: ${{ inputs.secondary_lessons }}
